name: PlayerForce
main: com.github.gorymoon.PlayerForce
version: 0.1

commands:
  PF:
    description: Access to the main PlayerForce command
    permission: force.admin

permissions:
  force.user:
    description: Gives you PF user abilities.
    default: true
  force.admin:
    description: Gives you PF admin abilities.
    default: false
    children:
      force.user: true